### ISSUE TITLE
No Local Changes in Rider?

### ISSUE THREAD

**Issue by jwheeler91** [microsoft/azure-devops-intellij#129]
Hi, I've not tried in InteliJ IDEA, but in Rider this plugin isn't finding my changes? Its pulled the repo down, but isn't showing differences so I can check in...

Any ideas?

**Comment by julia-vaseva** [comment]
Hi, I have just encountered this issue on Mac. For me, the plugin can detect changes only on Windows.  Logs attached.

Plugin version: 1.125.0
JetBrains Rider version: 2017.3.1

[idea_VSTS.log](https://github.com/Microsoft/vso-intellij/files/1789440/idea_VSTS.log)

**Comment by kaylangan** [comment]
@jwheeler91 are you using TFVC?

**Comment by dmitriysmirnovjb** [comment]
Workaround for authentication issue:
1.  Set TF_AUTO_SAVE_CREDENTIALS=1 env variable
2. Run `tf status /[ath/to/the/file -login:user@domain,password` command from the command line
3. Credentials will be cached and tf commands will work when called from IDE

**Comment by ForNeVeR** [comment]
Okay, here's the issue: `tf status` **always** require some authentication (even if it doesn't use it). And we never pass it explicitly for `tf status`.

On Windows, it works because if the authentication isn't explicitly passed, it tries to obtain Windows credentials (and, again, it never uses them when calculating the status, so it just works).

On macOS/Linux, `tf` isn't able to obtain Windows/Kerberos credentials, so it fails and requires user's attention.

We'll solve that by passing current valid credentials to `tf status` on non-Windows systems.
