### ISSUE TITLE
Create Workspace Fails

### ISSUE THREAD

**Issue by sehuff** [microsoft/azure-devops-intellij#368]
When I click on CreateWorkspace it appears to start working then just disappears.  IntellaJ then has a red ! that reports this error: (Note this is on a MAC)

com.microsoft.alm.plugin.external.exceptions.ToolBadExitCodeException: KEY_TF_BAD_EXIT_CODE
	at com.microsoft.alm.plugin.external.tools.TfTool.throwBadExitCode(TfTool.java:109)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:180)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

**Comment by ForNeVeR** [comment]
Could you please attach your IDE logs? `KEY_TF_BAD_EXIT_CODE` is not enough to diagnose the issue, because it isn't even clear which command it was executing.

**Comment by sehuff** [comment]
[idea.log](https://github.com/microsoft/azure-devops-intellij/files/4880545/idea.log)

**Comment by ForNeVeR** [comment]
Thanks, this clears it up. The main problem seems to be `java.lang.module.FindException: Module java.xml.bind not found` in the external `tf` process.

This is a known issue in the team-explorer-everywhere client: https://github.com/microsoft/team-explorer-everywhere/issues/237. Though it's the first time I see it manifest itself under an IDE, because we had applied special countermeasures against it (by explicitly disabling the client telemetry; it's only the telemetry module causing problems).

Could you please try our experimental client fork with telemetry completely removed from the code? Download TEE-CLC artifact from here: https://github.com/JetBrains/team-explorer-everywhere/releases/tag/14.135.1

According to our experience, it should work well on modern versions of macOS and IDEA.

**Comment by sehuff** [comment]
Thanks that has fixed the issue.  There isn't a Source Control Explorer in the plugin that allows you to branch and merge code visually is there?

**Comment by ForNeVeR** [comment]
Thanks for your answer! I'll now consider this issue as resolved (we have plans to include a link to download a new client in the plugin in future).

If I understand you correctly, then no, there's no such UI in the plugin, unfortunately.
