### ISSUE TITLE
I cannot contribute due to Java-Gradle incompatibility with Rider For Unreal Engine IDE

### ISSUE THREAD

**Issue by Karlovsky120** [microsoft/azure-devops-intellij#464]
I forked this repository and tried building it.

I'm trying to fix a few bugs I've encountered while using it with JetBrains Rider For Unreal Engine 2021.2.1, however I cannot get the plugin to build. I've followed your instructions in the readme but Java and Gradle versions are incompatible.

When I select Rider as IntelliJ SDK source (I'm assuming I have to select that if I want the plugin to be started with the Rider instance so I can test it there) I can only choose between corretto-11 and corretto-16 as Internal Java Platform. However, this project uses Gradle version 4.7 which is incompatible with both (the fact that version 4.8 is compatible with Java 11 (corretto-11) is really infuriating :D).

Have you thought about updating the project to a newer gradle version, at least version 4.8? The current gradle version is 7.3.1
Is there any other way I can make this work? I'm really trying to help here.

**Comment by ForNeVeR** [comment]
Hello.

Currently, the project is targeting Java 8 and Gradle 4.7, and there's a hard reason for that: since we support only certain IDEA versions (2019.3 or something right now, I believe), we cannot use newer versions of gradle-intellij-plugin. Which means we cannot use newer versions of Gradle, too. All the stuff is supposed to be moved forward together, and we are really trying to keep it up-to-date when possible.

For now, I recommend using the embedded configuration and external JDK 8 (AdoptOpenJDK should work well), building the plugin locally, and then installing it into your version of Rider from the file you built.

When debugging the plugin, I usually don't do it in Rider, since it has no Rider integration, and all of the plugin features are fully testable in IDEA.

**Comment by Karlovsky120** [comment]
Thank you for the explanation, I'll try to test it in IDEA then if it's all the same. I've ran the plugin with Rider 2021.2.1 and it has certain problems, I'll try to fix those without breaking anything.

For anyone stumbling into a similar problem, I've managed to sidestep it by setting Gradle JVM to a compatible version (version 1.8 in this particular case) in Settings > Build, Execution, Deployment > Build Tools > Gradle under azure-devops-intellij gradle project.
